name: 'NDepend'
description: 'NDepend parser'
inputs:
  NDependLicense:  # id of input
    description: 'NDepend license file'
    required: true
    default: ''
  Baseline:  # id of input
    description: 'NDepend baseline'
    required: false
    default: ''
  StopIfQGFailed:  # id of input
    description: 'Stop if at least one quality gate failed'
    required: false
    default: false
  NDependConfigFile:  # id of input
    description: 'Custom NDepend configuration file'
    required: false
    default: ''

runs:
  using: 'node12'
  main: 'dist/index.js'
